In [1]:
# data analysis and wrangling
import pandas as pd
import numpy as np
import random as rn
import seaborn as sns

# visualization
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
cou = pd.read_csv('/home/otavio/ml/datasets/utils/countries.csv')

In [3]:
flags = pd.read_csv('/home/otavio/ml/datasets/utils/flags.csv')

In [4]:
flags.drop('Images File Name', axis=1, inplace=True)

In [5]:
cou

     Index                                   Name Code               PT
0        0                            Afghanistan   AF      Afeganistão
1        1                          Aland Islands   AX      Ilhas Aland
2        2                                Albania   AL          Albânia
3        3                                Algeria   DZ          Argélia
4        4                         American Samoa   AS  Samoa Americana
..     ...                                    ...  ...              ...
249    249                                  Butan  NaN            Butão
250    250                                England  NaN       Inglaterra
251    251  Democratic People's Republic of Korea  NaN  Coréia do Norte
252    252                                Vietnam  NaN           Vietnã
253    253                                 Russia  NaN           Rússia

[254 rows x 4 columns]

In [6]:
cou = cou.merge(flags, left_on='Name', right_on='Country')
cou

,Index,Name,Code,PT,Country,ImageURL
0,0,Afghanistan,AF,Afeganistão,Afghanistan,https://upload.wikimedia.org/wikipedia/commons...
1,2,Albania,AL,Albânia,Albania,https://upload.wikimedia.org/wikipedia/commons...
2,3,Algeria,DZ,Argélia,Algeria,https://upload.wikimedia.org/wikipedia/commons...
3,5,Andorra,AD,Andorra,Andorra,https://upload.wikimedia.org/wikipedia/commons...
4,6,Angola,AO,Angola,Angola,https://upload.wikimedia.org/wikipedia/commons...
...,...,...,...,...,...,...
181,245,Yemen,YE,Iémen,Yemen,https://upload.wikimedia.org/wikipedia/commons...
182,246,Zambia,ZM,Zâmbia,Zambia,https://upload.wikimedia.org/wikipedia/commons...
183,247,Zimbabwe,ZW,Zimbábue,Zimbabwe,https://upload.wikimedia.org/wikipedia/commons...
184,252,Vietnam,NaN,Vietnã,Vietnam,https://upload.wikimedia.org/wikipedia/commons...
185,253,Russia,NaN,Rússia,Russia,https://upload.wikimedia.org/wikipedia/en/f/f3...

In [7]:
cou.drop('Country', axis=1, inplace=True)

In [9]:
cou.drop('Index', axis=1, inplace=True)

In [10]:
cou

,Name,Code,PT,ImageURL
0,Afghanistan,AF,Afeganistão,https://upload.wikimedia.org/wikipedia/commons...
1,Albania,AL,Albânia,https://upload.wikimedia.org/wikipedia/commons...
2,Algeria,DZ,Argélia,https://upload.wikimedia.org/wikipedia/commons...
3,Andorra,AD,Andorra,https://upload.wikimedia.org/wikipedia/commons...
4,Angola,AO,Angola,https://upload.wikimedia.org/wikipedia/commons...
...,...,...,...,...
181,Yemen,YE,Iémen,https://upload.wikimedia.org/wikipedia/commons...
182,Zambia,ZM,Zâmbia,https://upload.wikimedia.org/wikipedia/commons...
183,Zimbabwe,ZW,Zimbábue,https://upload.wikimedia.org/wikipedia/commons...
184,Vietnam,NaN,Vietnã,https://upload.wikimedia.org/wikipedia/commons...
185,Russia,NaN,Rússia,https://upload.wikimedia.org/wikipedia/en/f/f3...

In [11]:
cou.to_csv('countries.csv', index=False)