In [1]:
# data analysis and wrangling
import pandas as pd
import numpy as np
import seaborn as sns

# visualization
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data = pd.read_csv('/home/otavio/ml/datasets/world-data/life-expectancy.csv')

In [3]:
countries = pd.read_csv('/home/otavio/ml/datasets/utils/countries.csv')
data = data.merge(countries, how='left', left_on='Entity', right_on='Name')

In [4]:
# data = data[data['Year'] == 2016]
data = data[data['SubRegion'] == 'South America']

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 684 entries, 342 to 13461
Data columns (total 10 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Entity                                           684 non-null    object
 1   Code_x                                           684 non-null    object
 2   Year                                             684 non-null    int64
 3   Life expectancy at birth, total (years) (years)  684 non-null    float64
 4   Region                                           684 non-null    object
 5   SubRegion                                        684 non-null    object
 6   Name                                             684 non-null    object
 7   Code_y                                           684 non-null    object
 8   PT                                               684 non-null    object
 9   ImageURL                                         684 non-null    object
dtypes: float64(1), int64(1), object(8)
memory usage: 58.8+ KB

In [6]:
data = data.sort_values('Life expectancy at birth, total (years) (years)', ascending=False).reset_index()

In [7]:
data['Label'] = data['PT'] + ' (' + (data.index + 1).astype(str, copy=False) + 'º)'

In [8]:
data

,index,Entity,Code_x,Year,"Life expectancy at birth, total (years) (years)",Region,SubRegion,Name,Code_y,PT,ImageURL,Label
0,2244,Chile,CHL,2016,79.522,Americas,South America,Chile,CL,Chile,https://upload.wikimedia.org/wikipedia/commons...,Chile (1º)
1,2243,Chile,CHL,2015,79.315,Americas,South America,Chile,CL,Chile,https://upload.wikimedia.org/wikipedia/commons...,Chile (2º)
2,2242,Chile,CHL,2014,79.117,Americas,South America,Chile,CL,Chile,https://upload.wikimedia.org/wikipedia/commons...,Chile (3º)
3,2241,Chile,CHL,2013,78.931,Americas,South America,Chile,CL,Chile,https://upload.wikimedia.org/wikipedia/commons...,Chile (4º)
4,2240,Chile,CHL,2012,78.758,Americas,South America,Chile,CL,Chile,https://upload.wikimedia.org/wikipedia/commons...,Chile (5º)
...,...,...,...,...,...,...,...,...,...,...,...,...
679,1222,Bolivia,BOL,1964,43.451,Americas,South America,Bolivia,BO,Bolívia,https://upload.wikimedia.org/wikipedia/commons...,Bolívia (680º)
680,1221,Bolivia,BOL,1963,43.110,Americas,South America,Bolivia,BO,Bolívia,https://upload.wikimedia.org/wikipedia/commons...,Bolívia (681º)
681,1220,Bolivia,BOL,1962,42.778,Americas,South America,Bolivia,BO,Bolívia,https://upload.wikimedia.org/wikipedia/commons...,Bolívia (682º)
682,1219,Bolivia,BOL,1961,42.454,Americas,South America,Bolivia,BO,Bolívia,https://upload.wikimedia.org/wikipedia/commons...,Bolívia (683º)
683,1218,Bolivia,BOL,1960,42.138,Americas,South America,Bolivia,BO,Bolívia,https://upload.wikimedia.org/wikipedia/commons...,Bolívia (684º)

In [10]:
brasil = data[data['PT'] == 'Brasil']

In [34]:
new = data.pivot_table(index='Year', columns='PT', values=['Life expectancy at birth, total (years) (years)'])
new

     Life expectancy at birth, total (years) (years)                          \
PT                                         Argentina Bolívia  Brasil   Chile
Year
1960                                          65.022  42.138  54.241  57.285
1961                                          65.141  42.454  54.754  57.682
1962                                          65.233  42.778  55.270  58.097
1963                                          65.311  43.110  55.785  58.533
1964                                          65.388  43.451  56.293  58.993
1965                                          65.481  43.800  56.794  59.479
1966                                          65.603  44.157  57.289  59.994
1967                                          65.760  44.523  57.776  60.536
1968                                          65.953  44.898  58.254  61.104
1969                                          66.184  45.280  58.717  61.696
1970                                          66.449  45.671  59.154  62.311
1971                                          66.740  46.070  59.557  62.950
1972                                          67.044  46.477  59.919  63.609
1973                                          67.349  46.892  60.241  64.283
1974                                          67.652  47.315  60.527  64.967
1975                                          67.950  47.745  60.782  65.658
1976                                          68.248  48.183  61.017  66.355
1977                                          68.549  48.629  61.244  67.052
1978                                          68.856  49.082  61.476  67.744
1979                                          69.164  49.543  61.721  68.422
1980                                          69.464  50.012  61.983  69.074
1981                                          69.746  50.489  62.264  69.690
1982                                          70.003  50.974  62.559  70.265
1983                                          70.234  51.466  62.866  70.798
1984                                          70.438  51.965  63.185  71.288
1985                                          70.623  52.472  63.514  71.739
1986                                          70.797  52.986  63.852  72.157
1987                                          70.971  53.507  64.197  72.553
1988                                          71.155  54.034  64.552  72.936
1989                                          71.352  54.566  64.917  73.311
1990                                          71.565  55.104  65.300  73.680
1991                                          71.790  55.647  65.708  74.042
1992                                          72.023  56.195  66.144  74.394
1993                                          72.256  56.747  66.607  74.733
1994                                          72.489  57.303  67.095  75.059
1995                                          72.719  57.862  67.600  75.374
1996                                          72.947  58.423  68.112  75.678
1997                                          73.173  58.987  68.622  75.974
1998                                          73.397  59.554  69.120  76.259
1999                                          73.618  60.122  69.599  76.533
2000                                          73.832  60.690  70.055  76.793
2001                                          74.039  61.260  70.486  77.034
2002                                          74.236  61.829  70.896  77.255
2003                                          74.424  62.399  71.290  77.453
2004                                          74.603  62.968  71.670  77.632
2005                                          74.775  63.538  72.040  77.791
2006                                          74.941  64.113  72.405  77.934
2007                                          75.105  64.692  72.768  78.066
2008                                          75.268  65.272  73.129  78.193
2009                                          75.431  65.847  73.488  78.320
2010                                          75.595  66.408  73.838  78.454
2011                                          75.761  66.945  74.174  78.599
2012                                          75.926  67.451  74.488  78.758
2013                                          76.089  67.922  74.777  78.931
2014                                          76.252  68.357  75.042  79.117
2015                                          76.415  68.756  75.284  79.315
2016                                          76.577  69.125  75.509  79.522


PT   Colômbia Equador  Guiana Paraguai    Peru Suriname Uruguai Venezuela
Year
1960   56.752  53.236  60.260   63.879  47.694   59.660  67.782    59.253
1961   57.283  53.842  60.441   64.101  48.235   60.026  68.006    59.829
1962   57.775  54.409  60.623   64.307  48.754   60.386  68.197    60.395
1963   58.238  54.932  60.805   64.488  49.249   60.749  68.347    60.948
1964   58.678  55.407  60.984   64.644  49.728   61.117  68.454    61.488
1965   59.100  55.840  61.157   64.779  50.214   61.491  68.521    62.017
1966   59.500  56.237  61.317   64.903  50.737   61.867  68.554    62.539
1967   59.877  56.615  61.462   65.030  51.319   62.239  68.568    63.056
1968   60.233  56.992  61.588   65.169  51.971   62.599  68.576    63.570
1969   60.574  57.377  61.697   65.322  52.690   62.943  68.589    64.076
1970   60.910  57.783  61.789   65.486  53.457   63.268  68.617    64.569
1971   61.248  58.216  61.868   65.656  54.245   63.568  68.664    65.041
1972   61.598  58.678  61.938   65.821  55.022   63.844  68.732    65.485
1973   61.966  59.167  62.005   65.975  55.762   64.100  68.823    65.899
1974   62.360  59.682  62.072   66.116  56.454   64.339  68.939    66.279
1975   62.791  60.222  62.140   66.243  57.099   64.570  69.087    66.630
1976   63.271  60.781  62.211   66.360  57.706   64.806  69.269    66.956
1977   63.796  61.353  62.283   66.470  58.295   65.054  69.482    67.265
1978   64.354  61.930  62.355   66.578  58.881   65.315  69.721    67.560
1979   64.932  62.511  62.427   66.686  59.471   65.587  69.981    67.844
1980   65.506  63.095  62.498   66.793  60.065   65.863  70.255    68.114
1981   66.049  63.686  62.565   66.898  60.662   66.128  70.535    68.365
1982   66.541  64.286  62.626   67.000  61.254   66.371  70.814    68.593
1983   66.965  64.896  62.684   67.100  61.836   66.582  71.085    68.795
1984   67.315  65.511  62.741   67.199  62.406   66.758  71.343    68.975
1985   67.588  66.126  62.801   67.304  62.962   66.902  71.584    69.133
1986   67.789  66.735  62.869   67.417  63.503   67.019  71.805    69.274
1987   67.938  67.332  62.950   67.544  64.029   67.120  72.009    69.403
1988   68.060  67.910  63.046   67.687  64.542   67.214  72.203    69.529
1989   68.171  68.464  63.159   67.844  65.045   67.305  72.388    69.659
1990   68.292  68.990  63.290   68.014  65.541   67.393  72.571    69.804
1991   68.443  69.487  63.438   68.191  66.034   67.478  72.758    69.971
1992   68.630  69.956  63.600   68.370  66.528   67.554  72.954    70.165
1993   68.857  70.400  63.770   68.548  67.024   67.620  73.161    70.384
1994   69.125  70.820  63.946   68.727  67.523   67.677  73.381    70.628
1995   69.428  71.217  64.122   68.911  68.026   67.722  73.613    70.893
1996   69.756  71.594  64.297   69.108  68.533   67.751  73.854    71.176
1997   70.090  71.953  64.466   69.322  69.041   67.768  74.098    71.465
1998   70.416  72.297  64.630   69.556  69.544   67.781  74.341    71.752
1999   70.727  72.624  64.785   69.808  70.036   67.798  74.577    72.027
2000   71.019  72.933  64.930   70.070  70.512   67.838  74.805    72.281
2001   71.293  73.220  65.065   70.335  70.964   67.918  75.022    72.507
2002   71.556  73.482  65.192   70.593  71.389   68.051  75.229    72.704
2003   71.813  73.720  65.313   70.838  71.784   68.239  75.427    72.872
2004   72.062  73.937  65.428   71.067  72.146   68.480  75.614    73.015
2005   72.303  74.136  65.538   71.281  72.473   68.768  75.792    73.134
2006   72.532  74.322  65.642   71.485  72.764   69.089  75.961    73.235
2007   72.749  74.501  65.741   71.686  73.023   69.422  76.124    73.327
2008   72.952  74.678  65.836   71.887  73.258   69.749  76.282    73.419
2009   73.143  74.859  65.929   72.089  73.475   70.057  76.436    73.516
2010   73.325  75.046  66.022   72.285  73.681   70.335  76.588    73.625
2011   73.500  75.244  66.117   72.470  73.883   70.578  76.739    73.748
2012   73.673  75.449  66.216   72.638  74.088   70.790  76.890    73.885
2013   73.847  75.661  66.318   72.786  74.298   70.976  77.040    74.035
2014   74.022  75.879  66.425   72.913  74.518   71.138  77.190    74.196
2015   74.200  76.102  66.536   73.023  74.747   71.279  77.341    74.367
2016   74.381  76.327  66.650   73.120  74.983   71.405  77.493    74.545

In [37]:
new['SA'] = new.mean(axis=1)
# new.unstack().to_frame()
# br_sa = new[['Brasil', 'SA']]
# br_sa
new.to_csv('ehhe.csv')

In [9]:
# data.to_csv('out.csv', index=False)