In [2]:
# data analysis and wrangling
import pandas as pd
import numpy as np
import random as rn
import seaborn as sns

# visualization
import matplotlib.pyplot as plt
%matplotlib inline

In [16]:
data1 = pd.read_csv('/home/otavio/ml/datasets/world-data/health/death/annual-number-of-deaths-by-cause.csv')

In [17]:
data1

,Entity,Code,Year,Execution,Meningitis (deaths),Lower respiratory infections (deaths),Intestinal infectious diseases (deaths),Protein-energy malnutrition (deaths),Terrorism (deaths),Cardiovascular diseases (deaths),...,Neonatal disorders (deaths),Alcohol use disorders (deaths),Natural disasters (deaths),Diarrheal diseases (deaths),Heat (hot and cold exposure) (deaths),Nutritional deficiencies (deaths),Suicide (deaths),Conflict (deaths),Diabetes (deaths),Poisonings (deaths)
0,Afghanistan,AFG,1990,NaN,6469.977091,22836.912346,295.382207,1607.703797,12.0,46498.085024,...,18075.800290,75.595221,0.000000,8817.260208,226.789403,1667.386134,740.448500,1489.999290,3361.736409,170.742286
1,Afghanistan,AFG,1991,NaN,6347.158764,22325.633931,303.866598,1558.132316,68.0,46967.361037,...,18349.129972,76.109641,1349.999434,8588.463794,164.830417,1616.756233,762.245179,3370.000153,3362.470217,172.032657
2,Afghanistan,AFG,1992,NaN,6659.741428,23205.280750,317.750121,1617.721576,49.0,48355.558515,...,19982.149565,81.138310,614.000083,8924.932420,92.522183,1678.557625,856.912927,4343.997795,3445.705567,190.404111
3,Afghanistan,AFG,1993,NaN,8068.386263,28229.715397,333.978331,1931.808553,NaN,50072.563899,...,27291.235292,87.514744,109.999998,11976.501319,104.167461,2001.122436,975.603772,4097.000207,3563.236367,217.622614
4,Afghanistan,AFG,1994,NaN,9432.845127,32652.297630,348.419085,2351.629206,22.0,51416.815442,...,29862.680874,90.464149,160.000003,13296.448475,112.072652,2434.014268,1028.742412,8959.000461,3639.707847,236.240573
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6681,Zimbabwe,ZWE,2013,NaN,1820.090331,13108.151347,25.015658,3507.171892,1.0,16900.858090,...,9439.290155,73.649954,125.000002,5129.483596,44.403541,3557.450127,2561.496069,7.000000,2599.112561,410.802638
6682,Zimbabwe,ZWE,2014,NaN,1769.993458,12841.510671,25.623337,3380.319464,0.0,16755.843066,...,9106.657298,73.460128,8.500000,4946.075661,43.073231,3428.811706,2554.170577,3.000000,2625.681137,406.351616
6683,Zimbabwe,ZWE,2015,NaN,1728.691503,12637.728613,25.415872,3263.941226,NaN,16691.109079,...,8887.033499,74.605887,15.500000,4737.642966,42.139866,3310.899062,2583.031015,12.000000,2657.480378,404.641729
6684,Zimbabwe,ZWE,2016,NaN,1703.437894,12495.147292,25.752116,3188.723249,NaN,16781.946571,...,8653.776455,75.907792,31.000000,4602.100769,41.675497,3235.070735,2619.243794,6.000000,2712.995017,405.940831
6685,Zimbabwe,ZWE,2017,NaN,1677.007331,12369.654705,NaN,3111.873502,0.0,16976.902369,...,8411.915534,77.192339,0.000000,4602.593760,41.433611,3157.591804,2647.468528,5.000000,2746.739645,405.377266

In [18]:
data = data1[data1['Year'] == 2017]
data

,Entity,Code,Year,Execution,Meningitis (deaths),Lower respiratory infections (deaths),Intestinal infectious diseases (deaths),Protein-energy malnutrition (deaths),Terrorism (deaths),Cardiovascular diseases (deaths),...,Neonatal disorders (deaths),Alcohol use disorders (deaths),Natural disasters (deaths),Diarrheal diseases (deaths),Heat (hot and cold exposure) (deaths),Nutritional deficiencies (deaths),Suicide (deaths),Conflict (deaths),Diabetes (deaths),Poisonings (deaths)
27,Afghanistan,AFG,2017,NaN,6588.668300,2.143116e+04,NaN,1369.742538,6092.0,5.611858e+04,...,2.752174e+04,125.474868,155.000000,6.176201e+03,153.383019,1440.662274,1725.624776,1662.000127,5.978462e+03,365.394197
55,Albania,ALB,2017,NaN,18.606850,3.816531e+02,NaN,3.257634,0.0,1.214497e+04,...,1.836851e+02,15.465368,1.000000,6.939839e+00,10.528083,4.458938,161.977426,0.000000,1.350015e+02,11.384000
83,Algeria,DZA,2017,NaN,379.614524,4.723762e+03,NaN,80.517066,12.0,7.938907e+04,...,6.511280e+03,130.332484,0.000000,3.772447e+02,50.093911,97.704089,1698.665146,134.999996,5.201535e+03,366.645603
111,American Samoa,ASM,2017,NaN,0.731541,1.379903e+01,NaN,1.468605,NaN,9.984946e+01,...,4.608330e+00,0.344536,0.000000,1.180293e+00,1.142969,1.572362,3.481451,0.000000,3.324538e+01,0.407851
139,Andean Latin America,NaN,2017,NaN,581.273232,2.714703e+04,NaN,1759.381212,NaN,6.267408e+04,...,8.474229e+03,1015.506167,100.000000,2.145729e+03,274.305128,1994.021903,3263.203985,0.000000,1.159087e+04,419.109363
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6545,Western Sub-Saharan Africa,NaN,2017,NaN,97280.910306,3.555672e+05,NaN,56167.920226,NaN,3.432830e+05,...,3.520668e+05,4288.644450,399.003931,2.771202e+05,3609.520296,58239.213608,22262.875452,6222.060835,4.068288e+04,4219.994234
6573,World,OWID_WRL,2017,NaN,288021.105387,2.558606e+06,NaN,231770.992044,26445.0,1.779095e+07,...,1.783770e+06,184934.241760,9602.935057,1.569556e+06,53349.518780,269996.917689,793823.469135,129720.145674,1.369849e+06,72370.531920
6611,Yemen,YEM,2017,NaN,670.912350,6.365553e+03,NaN,652.747746,762.0,5.336712e+04,...,1.804043e+04,76.494244,50.000000,8.124504e+03,61.428043,745.360757,1469.601158,16810.957360,2.100061e+03,440.942178
6657,Zambia,ZMB,2017,NaN,2459.456832,8.979435e+03,NaN,2586.370661,0.0,1.215708e+04,...,9.688018e+03,202.315127,0.000000,7.748348e+03,19.930019,2637.116209,1160.836050,1.000000,2.351565e+03,180.807934
6685,Zimbabwe,ZWE,2017,NaN,1677.007331,1.236965e+04,NaN,3111.873502,0.0,1.697690e+04,...,8.411916e+03,77.192339,0.000000,4.602594e+03,41.433611,3157.591804,2647.468528,5.000000,2.746740e+03,405.377266